
package com.company;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CoffeeService", targetNamespace = "http://company.com/", wsdlLocation = "http://desktop-1m0cc2j:8080/lab166651262613553997/CoffeeService?wsdl")
public class CoffeeService
    extends Service
{

    private final static URL COFFEESERVICE_WSDL_LOCATION;
    private final static WebServiceException COFFEESERVICE_EXCEPTION;
    private final static QName COFFEESERVICE_QNAME = new QName("http://company.com/", "CoffeeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://desktop-1m0cc2j:8080/lab166651262613553997/CoffeeService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COFFEESERVICE_WSDL_LOCATION = url;
        COFFEESERVICE_EXCEPTION = e;
    }

    public CoffeeService() {
        super(__getWsdlLocation(), COFFEESERVICE_QNAME);
    }

    public CoffeeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COFFEESERVICE_QNAME, features);
    }

    public CoffeeService(URL wsdlLocation) {
        super(wsdlLocation, COFFEESERVICE_QNAME);
    }

    public CoffeeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COFFEESERVICE_QNAME, features);
    }

    public CoffeeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CoffeeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CoffeeEEWebService
     */
    @WebEndpoint(name = "CoffeeEEWebServicePort")
    public CoffeeEEWebService getCoffeeEEWebServicePort() {
        return super.getPort(new QName("http://company.com/", "CoffeeEEWebServicePort"), CoffeeEEWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CoffeeEEWebService
     */
    @WebEndpoint(name = "CoffeeEEWebServicePort")
    public CoffeeEEWebService getCoffeeEEWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://company.com/", "CoffeeEEWebServicePort"), CoffeeEEWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COFFEESERVICE_EXCEPTION!= null) {
            throw COFFEESERVICE_EXCEPTION;
        }
        return COFFEESERVICE_WSDL_LOCATION;
    }

}
