
package com.company;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CoffeeSortIllegalException", targetNamespace = "http://company.com/")
public class CoffeeSortIllegalException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CoffeeSortIllegalFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CoffeeSortIllegalException(String message, CoffeeSortIllegalFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CoffeeSortIllegalException(String message, CoffeeSortIllegalFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.company.CoffeeSortIllegalFault
     */
    public CoffeeSortIllegalFault getFaultInfo() {
        return faultInfo;
    }

}
